services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production

    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3