name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    steps:
      # 1. Check out code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # 3. Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Install dependencies via your setup script
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ./bin/setup.sh

      # 5. Run pytest via the official pytest GitHub Action
      - name: Run tests
        uses: pytest-dev/pytest-action@v2
        with:
          # pass any pytest args you like here
          args: --maxfail=1 --disable-warnings -q

      # 6. Lint with Flake8 using Reviewdog for inline PR comments
      - name: Lint with Flake8
        uses: reviewdog/action-flake8@v1
        with:
          reporter: github-pr-review
          # optionally customize flake8 flags:
          flake8_flags: --max-line-length=88
